config/routes.rb
# typed: false
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :feeds, only: [:show]
  resources :streams, only: [:show]

  root to: 'welcome#reader'

  get 'chronological', to: 'welcome#chronological', as: :chronological
  get 'reader', to: 'welcome#reader', as: :reader
end

app/models/stream.rb
class Stream < ApplicationRecord
  belongs_to :user, optional: true

  has_many :stream_assignments
  has_many :feeds, through: :stream_assignments

  has_many :entries, through: :feeds

  scope :sorted, -> { order(order: :asc) }
end

app/controllers/api/v3/streams_controller.rb
# typed: false
# frozen_string_literal: true

module Api
  module V3
    class StreamsController < Api::V3::ApiController # rubocop:disable Style/Documentation
      before_action :set_stream, only: %i[show update destroy]

      # GET /api/v3/streams
      def index
        @streams = Stream.all.includes(:feeds).page(pagination_params[:page]).per(default_per_page)
        render :index
      end

      # GET /api/v3/streams/:id
      def show
        render :show
      end

      # POST /api/v3/streams
      def create
        @stream = Stream.new(stream_params)
        if @stream.save
          render :show, status: :created
        else
          render json: @stream.errors, status: :unprocessable_entity
        end
      end

      # PATCH/PUT /api/v3/streams/:id
      def update
        if @stream.update(stream_params)
          render :show
        else
          render json: @stream.errors, status: :unprocessable_entity
        end
      end

      # DELETE /api/v3/streams/:id
      def destroy
        @stream.destroy
        head :no_content
      end

      private

      def set_stream
        @stream = Stream.find(params[:id])
      end

      def stream_params
        params.require(:stream).permit(:name, :permalink)
      end

      def default_per_page
        pagination_params[:per_page] || 100
      end

      def pagination_params
        params.slice(:page)
      end
    end
  end
end

app/controllers/streams_controller.rb
# typed: false
# frozen_string_literal: true

class StreamsController < ApplicationController
  before_action :set_controller_entities, only: :show

  # TODO: Access via readable permalink
  # TODO: Add RSS and JSON formats
  def show
    respond_to do |format|
      format.html { render layout: 'layouts/application' }
      format.js { render layout: false }
    end
  end

  private

  def set_controller_entities
    @streams = Stream.all.sorted
    @stream = Stream.find(filtered_params[:id])
    @feeds = @stream.feeds
    @entries = @stream.entries.for_feed.includes(:feed).page(filtered_params[:page]).per(default_per_page).chunk(&:feed)
  end

  def default_per_page
    filtered_params[:per_page] || 100
  end

  def filtered_params
    params.permit(:id, :page, :per_page, :js)
  end
end

app/helpers/streams_helper.rb
module StreamsHelper
end

app/views/streams/show.html.erb
<div class="flex flex-nowrap p-2 text-sm ml-auto gap-2 relative overflow-x-auto">
  <% @streams.each do |stream| %>
    <% if stream.id == @stream.id %>
      <% pill_class = "rounded-full bg-indigo-500 dark:bg-blue-500 text-white font-semibold px-3 py-1 flex-none" %>
    <% else  %>
      <% pill_class = "rounded-full bg-gray-300 dark:bg-gray-700 px-3 py-1 flex-none" %>
    <% end %>

    <%= link_to stream.name, stream_url(stream, request.query_parameters.slice(:l)), class: pill_class %>
  <% end %>
</div>

<section class="text-gray-600 body-font divide-y-2 dark:divide-dotted divide-gray-100 dark:divide-gray-700">
  <% @entries.each do |feed, feed_entries| %>
  <div class="py-1 flex flex-row flex-nowrap space-x-4 px-2">
    <div class="flex-none">
      <img class="w-8 h-8 lg:w-16 lg:h-16 rounded my-2 sticky top-2" src="<%= img_src_for_feed(feed) %>" />
    </div>

    <div class="flex-1">
      <% feed_entries.each do |entry| %>
        <%= render partial: "shared/entry", locals: { entry: entry } %>
      <% end %>
    </div>
  </div>
  <% end %>
</section>

<button id="back-to-top-button" title="Back To Top"
  class="hidden fixed z-90 bottom-8 right-8 border-0 w-12 h-12 rounded-full drop-shadow-md bg-indigo-500 dark:bg-blue-500 text-white text-3xl font-bold">&uarr;</button>