config/routes.rb
# typed: false
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :feeds, only: [:show]
  resources :streams, only: [:show]

  root to: 'welcome#reader'

  get 'chronological', to: 'welcome#chronological', as: :chronological
  get 'reader', to: 'welcome#reader', as: :reader
end

app/views/shared/_entry.html.erb
<div class="space-y-2 mb-6">
  <div class="flex flex-row justify-between">
    <p class="text-gray-500 dark:text-gray-300"><%= link_to entry.feed.title, feed_url(entry.feed) %></p>
    <p class="text-gray-500 dark:text-gray-300 text-xs" data-relative-timestamp="<%= timestamp_with_millis(entry.published_date) %>"><%= time_ago_in_words entry.published_date %> ago</p>
  </div>

  <h2 class="font-semibold text-gray-900 dark:text-white title-font"><%= entry.title %></h2>

  <p class="dark:text-gray-300 text-sm"><%= entry.description.truncate_words(80) %></p>
  <p class="dark:text-white text-sm font-semibold"><%= link_to entry.link&.truncate(80), entry.link, target: "_blank" %></p>

  <img class="rounded" src="<%= entry.readable_content.dig('table', 'lead_image_url') %>"  />
</div>

app/views/shared/_entry_compact.html.erb
<div class="py-1 flex flex-nowrap space-x-2 px-2">
    <div class="flex-grow space-y-1">
        <a href="<%= entry.real_uri %>" target="_blank">
            <h2 class="text-sm font-semibold text-gray-900 dark:text-white title-font"><%= entry.title %></h2>
        </a>
    </div>
</div>

app/views/shared/_entry_cozy.html.erb
<div class="py-1 flex flex-nowrap space-x-4 px-2">
  <div class=" flex-shrink-0 flex flex-col align-bottom">
    <img class="object-cover w-16 h-16 rounded my-auto" src="<%= img_src_for_entry(entry) %>" />
  </div>
  <div class="flex-grow space-y-1 my-2">
    <p class="text-gray-500 dark:text-gray-300 text-xs"><%= link_to entry.feed.title, feed_url(entry.feed) %></p>
    <a href="<%= entry.real_uri %>" target="_blank">
      <h2 class="font-semibold dark:font-normal text-gray-900 dark:text-white title-font"><%= entry.title %></h2>
    </a>
    <p class="text-gray-500 dark:text-gray-300 text-xs" data-relative-timestamp="<%= timestamp_with_millis(entry.published_date) %>"><%= time_ago_in_words entry.published_date %> ago</p>
  </div>
</div>

app/views/shared/_feed.html.erb
<% entry_partial = if local_assigns.fetch(:display_mode, :compact) == :compact then 'shared/entry_compact' else 'shared/entry' end %>

<section class="text-gray-600 dark:text-white body-font my-4">
    <div class="py-2 flex md:flex-nowrap space-x-2 px-2">
        <div class="flex w-3/5 flex-nowrap text-sm space-x-1">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-4 h-4">
                <path fill-rule="evenodd" d="M2 3.5A1.5 1.5 0 013.5 2h9A1.5 1.5 0 0114 3.5v11.75A2.75 2.75 0 0016.75 18h-12A2.75 2.75 0 012 15.25V3.5zm3.75 7a.75.75 0 000 1.5h4.5a.75.75 0 000-1.5h-4.5zm0 3a.75.75 0 000 1.5h4.5a.75.75 0 000-1.5h-4.5zM5 5.75A.75.75 0 015.75 5h4.5a.75.75 0 01.75.75v2.5a.75.75 0 01-.75.75h-4.5A.75.75 0 015 8.25v-2.5z" clip-rule="evenodd" />
                <path d="M16.5 6.5h-1v8.75a1.25 1.25 0 102.5 0V8a1.5 1.5 0 00-1.5-1.5z" />
            </svg>
            <span><%= link_to feed.title, feed_url(feed) %></span>
        </div>
        <div class="flex w-2/5 flex-nowrap flex-row text-sm justify-end space-x-4">
            <span class="flex flex-row flex-nowrap space-x-1">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-4 h-4">
                    <path d="M3.75 3a.75.75 0 00-.75.75v.5c0 .414.336.75.75.75H4c6.075 0 11 4.925 11 11v.25c0 .414.336.75.75.75h.5a.75.75 0 00.75-.75V16C17 8.82 11.18 3 4 3h-.25z" />
                    <path d="M3 8.75A.75.75 0 013.75 8H4a8 8 0 018 8v.25a.75.75 0 01-.75.75h-.5a.75.75 0 01-.75-.75V16a6 6 0 00-6-6h-.25A.75.75 0 013 9.25v-.5zM7 15a2 2 0 11-4 0 2 2 0 014 0z" />
                </svg>
                <%= link_to 'RSS', feed_url(feed, format: :rss) %>
            </span>
            <span class="flex flex-row flex-nowrap space-x-1">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-4 h-4">
                    <path d="M3.75 3a.75.75 0 00-.75.75v.5c0 .414.336.75.75.75H4c6.075 0 11 4.925 11 11v.25c0 .414.336.75.75.75h.5a.75.75 0 00.75-.75V16C17 8.82 11.18 3 4 3h-.25z" />
                    <path d="M3 8.75A.75.75 0 013.75 8H4a8 8 0 018 8v.25a.75.75 0 01-.75.75h-.5a.75.75 0 01-.75-.75V16a6 6 0 00-6-6h-.25A.75.75 0 013 9.25v-.5zM7 15a2 2 0 11-4 0 2 2 0 014 0z" />
                </svg>
                <%= link_to 'JSON', feed_url(feed, format: :json) %>
            </span>
        </div>
    </div>
    <div class="divide-y-2 dark:divide-dotted divide-gray-100 dark:divide-gray-700">
        <% entries.each do |entry| %>
            <%= render partial: entry_partial, locals: { entry: entry } %>
        <% end %>
    </div>
</section>